package org.eobjects.analyzer.job;

/**
 * Interface for job objects that generates outcomes.
 * 
 * @author Kasper Sørensen
 */
public interface OutcomeSourceJob {

	/**
	 * @return the outcomes generated by this job
	 */
	public Outcome[] getOutcomes();
}
