//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.06 at 11:00:22 AM CEST 
//


package org.eobjects.analyzer.configuration.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="configuration-metadata" type="{http://eobjects.org/analyzerbeans/configuration/1.0}configurationMetadataType" minOccurs="0"/>
 *         &lt;element name="datastore-catalog" type="{http://eobjects.org/analyzerbeans/configuration/1.0}datastoreCatalogType"/>
 *         &lt;choice>
 *           &lt;element name="multithreaded-taskrunner" type="{http://eobjects.org/analyzerbeans/configuration/1.0}multithreadedTaskrunnerType"/>
 *           &lt;element name="singlethreaded-taskrunner" type="{http://eobjects.org/analyzerbeans/configuration/1.0}singlethreadedTaskrunnerType"/>
 *           &lt;element name="custom-taskrunner" type="{http://eobjects.org/analyzerbeans/configuration/1.0}customTaskrunnerType"/>
 *         &lt;/choice>
 *         &lt;element name="classpath-scanner" type="{http://eobjects.org/analyzerbeans/configuration/1.0}classpathScannerType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "configurationMetadata",
    "datastoreCatalog",
    "multithreadedTaskrunner",
    "singlethreadedTaskrunner",
    "customTaskrunner",
    "classpathScanner"
})
@XmlRootElement(name = "configuration")
public class Configuration {

    @XmlElement(name = "configuration-metadata")
    protected ConfigurationMetadataType configurationMetadata;
    @XmlElement(name = "datastore-catalog", required = true)
    protected DatastoreCatalogType datastoreCatalog;
    @XmlElement(name = "multithreaded-taskrunner")
    protected MultithreadedTaskrunnerType multithreadedTaskrunner;
    @XmlElement(name = "singlethreaded-taskrunner")
    protected SinglethreadedTaskrunnerType singlethreadedTaskrunner;
    @XmlElement(name = "custom-taskrunner")
    protected CustomTaskrunnerType customTaskrunner;
    @XmlElement(name = "classpath-scanner")
    protected ClasspathScannerType classpathScanner;

    /**
     * Gets the value of the configurationMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigurationMetadataType }
     *     
     */
    public ConfigurationMetadataType getConfigurationMetadata() {
        return configurationMetadata;
    }

    /**
     * Sets the value of the configurationMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigurationMetadataType }
     *     
     */
    public void setConfigurationMetadata(ConfigurationMetadataType value) {
        this.configurationMetadata = value;
    }

    /**
     * Gets the value of the datastoreCatalog property.
     * 
     * @return
     *     possible object is
     *     {@link DatastoreCatalogType }
     *     
     */
    public DatastoreCatalogType getDatastoreCatalog() {
        return datastoreCatalog;
    }

    /**
     * Sets the value of the datastoreCatalog property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatastoreCatalogType }
     *     
     */
    public void setDatastoreCatalog(DatastoreCatalogType value) {
        this.datastoreCatalog = value;
    }

    /**
     * Gets the value of the multithreadedTaskrunner property.
     * 
     * @return
     *     possible object is
     *     {@link MultithreadedTaskrunnerType }
     *     
     */
    public MultithreadedTaskrunnerType getMultithreadedTaskrunner() {
        return multithreadedTaskrunner;
    }

    /**
     * Sets the value of the multithreadedTaskrunner property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultithreadedTaskrunnerType }
     *     
     */
    public void setMultithreadedTaskrunner(MultithreadedTaskrunnerType value) {
        this.multithreadedTaskrunner = value;
    }

    /**
     * Gets the value of the singlethreadedTaskrunner property.
     * 
     * @return
     *     possible object is
     *     {@link SinglethreadedTaskrunnerType }
     *     
     */
    public SinglethreadedTaskrunnerType getSinglethreadedTaskrunner() {
        return singlethreadedTaskrunner;
    }

    /**
     * Sets the value of the singlethreadedTaskrunner property.
     * 
     * @param value
     *     allowed object is
     *     {@link SinglethreadedTaskrunnerType }
     *     
     */
    public void setSinglethreadedTaskrunner(SinglethreadedTaskrunnerType value) {
        this.singlethreadedTaskrunner = value;
    }

    /**
     * Gets the value of the customTaskrunner property.
     * 
     * @return
     *     possible object is
     *     {@link CustomTaskrunnerType }
     *     
     */
    public CustomTaskrunnerType getCustomTaskrunner() {
        return customTaskrunner;
    }

    /**
     * Sets the value of the customTaskrunner property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomTaskrunnerType }
     *     
     */
    public void setCustomTaskrunner(CustomTaskrunnerType value) {
        this.customTaskrunner = value;
    }

    /**
     * Gets the value of the classpathScanner property.
     * 
     * @return
     *     possible object is
     *     {@link ClasspathScannerType }
     *     
     */
    public ClasspathScannerType getClasspathScanner() {
        return classpathScanner;
    }

    /**
     * Sets the value of the classpathScanner property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClasspathScannerType }
     *     
     */
    public void setClasspathScanner(ClasspathScannerType value) {
        this.classpathScanner = value;
    }

}
