/**
 * eobjects.org AnalyzerBeans
 * Copyright (C) 2010 eobjects.org
 *
 * This copyrighted material is made available to anyone wishing to use, modify,
 * copy, or redistribute it subject to the terms and conditions of the GNU
 * Lesser General Public License, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this distribution; if not, write to:
 * Free Software Foundation, Inc.
 * 51 Franklin Street, Fifth Floor
 * Boston, MA  02110-1301  USA
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.05 at 10:05:31 AM CET 
//


package org.eobjects.analyzer.configuration.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="configuration-metadata" type="{http://eobjects.org/analyzerbeans/configuration/1.0}configurationMetadataType" minOccurs="0"/>
 *         &lt;element name="datastore-catalog" type="{http://eobjects.org/analyzerbeans/configuration/1.0}datastoreCatalogType"/>
 *         &lt;element name="reference-data-catalog" type="{http://eobjects.org/analyzerbeans/configuration/1.0}referenceDataCatalogType" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="multithreaded-taskrunner" type="{http://eobjects.org/analyzerbeans/configuration/1.0}multithreadedTaskrunnerType"/>
 *           &lt;element name="singlethreaded-taskrunner" type="{http://eobjects.org/analyzerbeans/configuration/1.0}singlethreadedTaskrunnerType"/>
 *           &lt;element name="custom-taskrunner" type="{http://eobjects.org/analyzerbeans/configuration/1.0}customElementType"/>
 *         &lt;/choice>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="in-memory-storage-provider" type="{http://eobjects.org/analyzerbeans/configuration/1.0}inMemoryStorageProviderType"/>
 *           &lt;element name="hsqldb-storage-provider" type="{http://eobjects.org/analyzerbeans/configuration/1.0}hsqldbStorageProviderType"/>
 *           &lt;element name="h2-database-storage-provider" type="{http://eobjects.org/analyzerbeans/configuration/1.0}h2StorageProviderType"/>
 *           &lt;element name="berkeley-db-storage-provider" type="{http://eobjects.org/analyzerbeans/configuration/1.0}berkeleyDbStorageProviderType"/>
 *           &lt;element name="custom-storage-provider" type="{http://eobjects.org/analyzerbeans/configuration/1.0}customElementType"/>
 *         &lt;/choice>
 *         &lt;element name="classpath-scanner" type="{http://eobjects.org/analyzerbeans/configuration/1.0}classpathScannerType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "configurationMetadata",
    "datastoreCatalog",
    "referenceDataCatalog",
    "multithreadedTaskrunner",
    "singlethreadedTaskrunner",
    "customTaskrunner",
    "inMemoryStorageProvider",
    "hsqldbStorageProvider",
    "h2DatabaseStorageProvider",
    "berkeleyDbStorageProvider",
    "customStorageProvider",
    "classpathScanner"
})
@XmlRootElement(name = "configuration")
public class Configuration {

    @XmlElement(name = "configuration-metadata")
    protected ConfigurationMetadataType configurationMetadata;
    @XmlElement(name = "datastore-catalog", required = true)
    protected DatastoreCatalogType datastoreCatalog;
    @XmlElement(name = "reference-data-catalog")
    protected ReferenceDataCatalogType referenceDataCatalog;
    @XmlElement(name = "multithreaded-taskrunner")
    protected MultithreadedTaskrunnerType multithreadedTaskrunner;
    @XmlElement(name = "singlethreaded-taskrunner")
    protected SinglethreadedTaskrunnerType singlethreadedTaskrunner;
    @XmlElement(name = "custom-taskrunner")
    protected CustomElementType customTaskrunner;
    @XmlElement(name = "in-memory-storage-provider")
    protected InMemoryStorageProviderType inMemoryStorageProvider;
    @XmlElement(name = "hsqldb-storage-provider")
    protected HsqldbStorageProviderType hsqldbStorageProvider;
    @XmlElement(name = "h2-database-storage-provider")
    protected H2StorageProviderType h2DatabaseStorageProvider;
    @XmlElement(name = "berkeley-db-storage-provider")
    protected BerkeleyDbStorageProviderType berkeleyDbStorageProvider;
    @XmlElement(name = "custom-storage-provider")
    protected CustomElementType customStorageProvider;
    @XmlElement(name = "classpath-scanner")
    protected ClasspathScannerType classpathScanner;

    /**
     * Gets the value of the configurationMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigurationMetadataType }
     *     
     */
    public ConfigurationMetadataType getConfigurationMetadata() {
        return configurationMetadata;
    }

    /**
     * Sets the value of the configurationMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigurationMetadataType }
     *     
     */
    public void setConfigurationMetadata(ConfigurationMetadataType value) {
        this.configurationMetadata = value;
    }

    /**
     * Gets the value of the datastoreCatalog property.
     * 
     * @return
     *     possible object is
     *     {@link DatastoreCatalogType }
     *     
     */
    public DatastoreCatalogType getDatastoreCatalog() {
        return datastoreCatalog;
    }

    /**
     * Sets the value of the datastoreCatalog property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatastoreCatalogType }
     *     
     */
    public void setDatastoreCatalog(DatastoreCatalogType value) {
        this.datastoreCatalog = value;
    }

    /**
     * Gets the value of the referenceDataCatalog property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceDataCatalogType }
     *     
     */
    public ReferenceDataCatalogType getReferenceDataCatalog() {
        return referenceDataCatalog;
    }

    /**
     * Sets the value of the referenceDataCatalog property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceDataCatalogType }
     *     
     */
    public void setReferenceDataCatalog(ReferenceDataCatalogType value) {
        this.referenceDataCatalog = value;
    }

    /**
     * Gets the value of the multithreadedTaskrunner property.
     * 
     * @return
     *     possible object is
     *     {@link MultithreadedTaskrunnerType }
     *     
     */
    public MultithreadedTaskrunnerType getMultithreadedTaskrunner() {
        return multithreadedTaskrunner;
    }

    /**
     * Sets the value of the multithreadedTaskrunner property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultithreadedTaskrunnerType }
     *     
     */
    public void setMultithreadedTaskrunner(MultithreadedTaskrunnerType value) {
        this.multithreadedTaskrunner = value;
    }

    /**
     * Gets the value of the singlethreadedTaskrunner property.
     * 
     * @return
     *     possible object is
     *     {@link SinglethreadedTaskrunnerType }
     *     
     */
    public SinglethreadedTaskrunnerType getSinglethreadedTaskrunner() {
        return singlethreadedTaskrunner;
    }

    /**
     * Sets the value of the singlethreadedTaskrunner property.
     * 
     * @param value
     *     allowed object is
     *     {@link SinglethreadedTaskrunnerType }
     *     
     */
    public void setSinglethreadedTaskrunner(SinglethreadedTaskrunnerType value) {
        this.singlethreadedTaskrunner = value;
    }

    /**
     * Gets the value of the customTaskrunner property.
     * 
     * @return
     *     possible object is
     *     {@link CustomElementType }
     *     
     */
    public CustomElementType getCustomTaskrunner() {
        return customTaskrunner;
    }

    /**
     * Sets the value of the customTaskrunner property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomElementType }
     *     
     */
    public void setCustomTaskrunner(CustomElementType value) {
        this.customTaskrunner = value;
    }

    /**
     * Gets the value of the inMemoryStorageProvider property.
     * 
     * @return
     *     possible object is
     *     {@link InMemoryStorageProviderType }
     *     
     */
    public InMemoryStorageProviderType getInMemoryStorageProvider() {
        return inMemoryStorageProvider;
    }

    /**
     * Sets the value of the inMemoryStorageProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link InMemoryStorageProviderType }
     *     
     */
    public void setInMemoryStorageProvider(InMemoryStorageProviderType value) {
        this.inMemoryStorageProvider = value;
    }

    /**
     * Gets the value of the hsqldbStorageProvider property.
     * 
     * @return
     *     possible object is
     *     {@link HsqldbStorageProviderType }
     *     
     */
    public HsqldbStorageProviderType getHsqldbStorageProvider() {
        return hsqldbStorageProvider;
    }

    /**
     * Sets the value of the hsqldbStorageProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link HsqldbStorageProviderType }
     *     
     */
    public void setHsqldbStorageProvider(HsqldbStorageProviderType value) {
        this.hsqldbStorageProvider = value;
    }

    /**
     * Gets the value of the h2DatabaseStorageProvider property.
     * 
     * @return
     *     possible object is
     *     {@link H2StorageProviderType }
     *     
     */
    public H2StorageProviderType getH2DatabaseStorageProvider() {
        return h2DatabaseStorageProvider;
    }

    /**
     * Sets the value of the h2DatabaseStorageProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link H2StorageProviderType }
     *     
     */
    public void setH2DatabaseStorageProvider(H2StorageProviderType value) {
        this.h2DatabaseStorageProvider = value;
    }

    /**
     * Gets the value of the berkeleyDbStorageProvider property.
     * 
     * @return
     *     possible object is
     *     {@link BerkeleyDbStorageProviderType }
     *     
     */
    public BerkeleyDbStorageProviderType getBerkeleyDbStorageProvider() {
        return berkeleyDbStorageProvider;
    }

    /**
     * Sets the value of the berkeleyDbStorageProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link BerkeleyDbStorageProviderType }
     *     
     */
    public void setBerkeleyDbStorageProvider(BerkeleyDbStorageProviderType value) {
        this.berkeleyDbStorageProvider = value;
    }

    /**
     * Gets the value of the customStorageProvider property.
     * 
     * @return
     *     possible object is
     *     {@link CustomElementType }
     *     
     */
    public CustomElementType getCustomStorageProvider() {
        return customStorageProvider;
    }

    /**
     * Sets the value of the customStorageProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomElementType }
     *     
     */
    public void setCustomStorageProvider(CustomElementType value) {
        this.customStorageProvider = value;
    }

    /**
     * Gets the value of the classpathScanner property.
     * 
     * @return
     *     possible object is
     *     {@link ClasspathScannerType }
     *     
     */
    public ClasspathScannerType getClasspathScanner() {
        return classpathScanner;
    }

    /**
     * Sets the value of the classpathScanner property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClasspathScannerType }
     *     
     */
    public void setClasspathScanner(ClasspathScannerType value) {
        this.classpathScanner = value;
    }

}
