//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.29 at 03:12:48 PM CEST 
//


package org.eobjects.analyzer.configuration.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for referenceDataCatalogType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="referenceDataCatalogType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dictionaries" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="text-file-dictionary" type="{http://eobjects.org/analyzerbeans/configuration/1.0}textFileDictionaryType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="value-list-dictionary" type="{http://eobjects.org/analyzerbeans/configuration/1.0}valueListDictionaryType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="datastore-dictionary" type="{http://eobjects.org/analyzerbeans/configuration/1.0}datastoreDictionaryType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="custom-dictionary" type="{http://eobjects.org/analyzerbeans/configuration/1.0}customElementType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="synonym-catalogs" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="text-file-synonym-catalog" type="{http://eobjects.org/analyzerbeans/configuration/1.0}textFileSynonymCatalogType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="custom-synonym-catalog" type="{http://eobjects.org/analyzerbeans/configuration/1.0}customElementType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "referenceDataCatalogType", propOrder = {
    "dictionaries",
    "synonymCatalogs"
})
public class ReferenceDataCatalogType {

    protected ReferenceDataCatalogType.Dictionaries dictionaries;
    @XmlElement(name = "synonym-catalogs")
    protected ReferenceDataCatalogType.SynonymCatalogs synonymCatalogs;

    /**
     * Gets the value of the dictionaries property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceDataCatalogType.Dictionaries }
     *     
     */
    public ReferenceDataCatalogType.Dictionaries getDictionaries() {
        return dictionaries;
    }

    /**
     * Sets the value of the dictionaries property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceDataCatalogType.Dictionaries }
     *     
     */
    public void setDictionaries(ReferenceDataCatalogType.Dictionaries value) {
        this.dictionaries = value;
    }

    /**
     * Gets the value of the synonymCatalogs property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceDataCatalogType.SynonymCatalogs }
     *     
     */
    public ReferenceDataCatalogType.SynonymCatalogs getSynonymCatalogs() {
        return synonymCatalogs;
    }

    /**
     * Sets the value of the synonymCatalogs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceDataCatalogType.SynonymCatalogs }
     *     
     */
    public void setSynonymCatalogs(ReferenceDataCatalogType.SynonymCatalogs value) {
        this.synonymCatalogs = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="text-file-dictionary" type="{http://eobjects.org/analyzerbeans/configuration/1.0}textFileDictionaryType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="value-list-dictionary" type="{http://eobjects.org/analyzerbeans/configuration/1.0}valueListDictionaryType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="datastore-dictionary" type="{http://eobjects.org/analyzerbeans/configuration/1.0}datastoreDictionaryType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="custom-dictionary" type="{http://eobjects.org/analyzerbeans/configuration/1.0}customElementType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "textFileDictionaryOrValueListDictionaryOrDatastoreDictionary"
    })
    public static class Dictionaries {

        @XmlElements({
            @XmlElement(name = "datastore-dictionary", type = DatastoreDictionaryType.class),
            @XmlElement(name = "value-list-dictionary", type = ValueListDictionaryType.class),
            @XmlElement(name = "custom-dictionary", type = CustomElementType.class),
            @XmlElement(name = "text-file-dictionary", type = TextFileDictionaryType.class)
        })
        protected List<Object> textFileDictionaryOrValueListDictionaryOrDatastoreDictionary;

        /**
         * Gets the value of the textFileDictionaryOrValueListDictionaryOrDatastoreDictionary property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the textFileDictionaryOrValueListDictionaryOrDatastoreDictionary property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTextFileDictionaryOrValueListDictionaryOrDatastoreDictionary().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DatastoreDictionaryType }
         * {@link ValueListDictionaryType }
         * {@link CustomElementType }
         * {@link TextFileDictionaryType }
         * 
         * 
         */
        public List<Object> getTextFileDictionaryOrValueListDictionaryOrDatastoreDictionary() {
            if (textFileDictionaryOrValueListDictionaryOrDatastoreDictionary == null) {
                textFileDictionaryOrValueListDictionaryOrDatastoreDictionary = new ArrayList<Object>();
            }
            return this.textFileDictionaryOrValueListDictionaryOrDatastoreDictionary;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="text-file-synonym-catalog" type="{http://eobjects.org/analyzerbeans/configuration/1.0}textFileSynonymCatalogType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="custom-synonym-catalog" type="{http://eobjects.org/analyzerbeans/configuration/1.0}customElementType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "textFileSynonymCatalogOrCustomSynonymCatalog"
    })
    public static class SynonymCatalogs {

        @XmlElements({
            @XmlElement(name = "text-file-synonym-catalog", type = TextFileSynonymCatalogType.class),
            @XmlElement(name = "custom-synonym-catalog", type = CustomElementType.class)
        })
        protected List<Object> textFileSynonymCatalogOrCustomSynonymCatalog;

        /**
         * Gets the value of the textFileSynonymCatalogOrCustomSynonymCatalog property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the textFileSynonymCatalogOrCustomSynonymCatalog property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTextFileSynonymCatalogOrCustomSynonymCatalog().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TextFileSynonymCatalogType }
         * {@link CustomElementType }
         * 
         * 
         */
        public List<Object> getTextFileSynonymCatalogOrCustomSynonymCatalog() {
            if (textFileSynonymCatalogOrCustomSynonymCatalog == null) {
                textFileSynonymCatalogOrCustomSynonymCatalog = new ArrayList<Object>();
            }
            return this.textFileSynonymCatalogOrCustomSynonymCatalog;
        }

    }

}
