/**
 * eobjects.org AnalyzerBeans
 * Copyright (C) 2010 eobjects.org
 *
 * This copyrighted material is made available to anyone wishing to use, modify,
 * copy, or redistribute it subject to the terms and conditions of the GNU
 * Lesser General Public License, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this distribution; if not, write to:
 * Free Software Foundation, Inc.
 * 51 Franklin Street, Fifth Floor
 * Boston, MA  02110-1301  USA
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.02 at 04:34:15 PM CET 
//


package org.eobjects.analyzer.configuration.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for storageProviderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="storageProviderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="combined" type="{http://eobjects.org/analyzerbeans/configuration/1.0}combinedStorageProviderType"/>
 *         &lt;element name="in-memory" type="{http://eobjects.org/analyzerbeans/configuration/1.0}inMemoryStorageProviderType"/>
 *         &lt;element name="h2-database" type="{http://eobjects.org/analyzerbeans/configuration/1.0}h2StorageProviderType"/>
 *         &lt;element name="hsqldb" type="{http://eobjects.org/analyzerbeans/configuration/1.0}hsqldbStorageProviderType"/>
 *         &lt;element name="berkeley-db" type="{http://eobjects.org/analyzerbeans/configuration/1.0}berkeleyDbStorageProviderType"/>
 *         &lt;element name="custom-storage-provider" type="{http://eobjects.org/analyzerbeans/configuration/1.0}customElementType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "storageProviderType", propOrder = {
    "combined",
    "inMemory",
    "h2Database",
    "hsqldb",
    "berkeleyDb",
    "customStorageProvider"
})
public class StorageProviderType {

    protected CombinedStorageProviderType combined;
    @XmlElement(name = "in-memory")
    protected InMemoryStorageProviderType inMemory;
    @XmlElement(name = "h2-database")
    protected H2StorageProviderType h2Database;
    protected HsqldbStorageProviderType hsqldb;
    @XmlElement(name = "berkeley-db")
    protected BerkeleyDbStorageProviderType berkeleyDb;
    @XmlElement(name = "custom-storage-provider")
    protected CustomElementType customStorageProvider;

    /**
     * Gets the value of the combined property.
     * 
     * @return
     *     possible object is
     *     {@link CombinedStorageProviderType }
     *     
     */
    public CombinedStorageProviderType getCombined() {
        return combined;
    }

    /**
     * Sets the value of the combined property.
     * 
     * @param value
     *     allowed object is
     *     {@link CombinedStorageProviderType }
     *     
     */
    public void setCombined(CombinedStorageProviderType value) {
        this.combined = value;
    }

    /**
     * Gets the value of the inMemory property.
     * 
     * @return
     *     possible object is
     *     {@link InMemoryStorageProviderType }
     *     
     */
    public InMemoryStorageProviderType getInMemory() {
        return inMemory;
    }

    /**
     * Sets the value of the inMemory property.
     * 
     * @param value
     *     allowed object is
     *     {@link InMemoryStorageProviderType }
     *     
     */
    public void setInMemory(InMemoryStorageProviderType value) {
        this.inMemory = value;
    }

    /**
     * Gets the value of the h2Database property.
     * 
     * @return
     *     possible object is
     *     {@link H2StorageProviderType }
     *     
     */
    public H2StorageProviderType getH2Database() {
        return h2Database;
    }

    /**
     * Sets the value of the h2Database property.
     * 
     * @param value
     *     allowed object is
     *     {@link H2StorageProviderType }
     *     
     */
    public void setH2Database(H2StorageProviderType value) {
        this.h2Database = value;
    }

    /**
     * Gets the value of the hsqldb property.
     * 
     * @return
     *     possible object is
     *     {@link HsqldbStorageProviderType }
     *     
     */
    public HsqldbStorageProviderType getHsqldb() {
        return hsqldb;
    }

    /**
     * Sets the value of the hsqldb property.
     * 
     * @param value
     *     allowed object is
     *     {@link HsqldbStorageProviderType }
     *     
     */
    public void setHsqldb(HsqldbStorageProviderType value) {
        this.hsqldb = value;
    }

    /**
     * Gets the value of the berkeleyDb property.
     * 
     * @return
     *     possible object is
     *     {@link BerkeleyDbStorageProviderType }
     *     
     */
    public BerkeleyDbStorageProviderType getBerkeleyDb() {
        return berkeleyDb;
    }

    /**
     * Sets the value of the berkeleyDb property.
     * 
     * @param value
     *     allowed object is
     *     {@link BerkeleyDbStorageProviderType }
     *     
     */
    public void setBerkeleyDb(BerkeleyDbStorageProviderType value) {
        this.berkeleyDb = value;
    }

    /**
     * Gets the value of the customStorageProvider property.
     * 
     * @return
     *     possible object is
     *     {@link CustomElementType }
     *     
     */
    public CustomElementType getCustomStorageProvider() {
        return customStorageProvider;
    }

    /**
     * Sets the value of the customStorageProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomElementType }
     *     
     */
    public void setCustomStorageProvider(CustomElementType value) {
        this.customStorageProvider = value;
    }

}
