//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.28 at 05:39:23 PM CEST 
//


package org.eobjects.analyzer.job.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for providedPropertyTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="providedPropertyTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="list"/>
 *     &lt;enumeration value="map"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "providedPropertyTypeEnum")
@XmlEnum
public enum ProvidedPropertyTypeEnum {

    @XmlEnumValue("list")
    LIST("list"),
    @XmlEnumValue("map")
    MAP("map");
    private final String value;

    ProvidedPropertyTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ProvidedPropertyTypeEnum fromValue(String v) {
        for (ProvidedPropertyTypeEnum c: ProvidedPropertyTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
