//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.01 at 01:29:32 PM CET 
//


package org.eobjects.analyzer.job.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for transformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="transformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="transformer" type="{http://eobjects.org/analyzerbeans/job/1.0}transformerType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="filter" type="{http://eobjects.org/analyzerbeans/job/1.0}filterType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="merged-outcome" type="{http://eobjects.org/analyzerbeans/job/1.0}mergedOutcomeType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "transformationType", propOrder = {
    "transformerOrFilterOrMergedOutcome"
})
public class TransformationType {

    @XmlElements({
        @XmlElement(name = "merged-outcome", type = MergedOutcomeType.class),
        @XmlElement(name = "transformer", type = TransformerType.class),
        @XmlElement(name = "filter", type = FilterType.class)
    })
    protected List<Object> transformerOrFilterOrMergedOutcome;

    /**
     * Gets the value of the transformerOrFilterOrMergedOutcome property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transformerOrFilterOrMergedOutcome property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransformerOrFilterOrMergedOutcome().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MergedOutcomeType }
     * {@link TransformerType }
     * {@link FilterType }
     * 
     * 
     */
    public List<Object> getTransformerOrFilterOrMergedOutcome() {
        if (transformerOrFilterOrMergedOutcome == null) {
            transformerOrFilterOrMergedOutcome = new ArrayList<Object>();
        }
        return this.transformerOrFilterOrMergedOutcome;
    }

}
